{
 "title": "APC UPS",
 "description": "Prometheus apcupsd Exporter",
 "tags": [ "prometheus" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Time on Battery",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "apcupsd_battery_time_on_seconds"
    }
   ]
  },
  {
   "title": "Time Remaining",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "apcupsd_battery_time_left_seconds "
    }
   ]
  },
  {
   "title": "UPS Load",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    { "expr": "apcupsd_ups_load_percent" }
   ]
  },
  {
   "title": "Battery Charge",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    { "expr": "apcupsd_battery_charge_percent" }
   ]
  },
  {
   "title": "Line Voltage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    { "expr": "apcupsd_line_volts" }
   ]
  },
  {
   "title": "UPS Health",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "apcupsd_battery_charge_percent", "legendFormat": "Battery Charge" },
    {
     "expr": "apcupsd_battery_time_left_seconds",
     "legendFormat": "Time Remaining"
    },
    { "expr": "apcupsd_ups_load_percent", "legendFormat": "UPS Load" }
   ]
  },
  {
   "title": "Line Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    { "expr": "apcupsd_line_volts", "legendFormat": "Line Voltage" },
    { "expr": "apcupsd_line_nominal_volts", "legendFormat": "Nominal Line Voltage" }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    { "expr": "apcupsd_battery_volts", "legendFormat": "Battery Voltage" },
    { "expr": "apcupsd_battery_nominal_volts", "legendFormat": "Nominal Battery Voltage" }
   ]
  }
 ]
}